WIP: samples: ros2: add step to ros2
Linaro/step pull request #22
Opened 2022-07-27 21:30 UTC by uLipe

sample streaming sensor data.

Signed-off-by: Felipe <felipe.neves@linaro.org>

2022-07-28 14:20 UTC, microbuilder commented on samples/ros2_to_step_bridge/README.rst
> +Secure Telemetry Pipeline (STeP) ROS2 exammple
Typo in the title (just doing a quick browse, won't be able to test right away)

2022-07-28 14:21 UTC, uLipe commented on samples/ros2_to_step_bridge/README.rst
> +Secure Telemetry Pipeline (STeP) ROS2 exammple
Ah yes, this is currently broken for testing, until some micro ros side gets fixed.

2022-08-04 17:59 UTC, uLipe commented
Just waiting microros module to be updated, with latest addtions from ROS2 to resume this one.

2022-09-07 12:27 UTC, microbuilder requested changes

2022-09-07 12:27 UTC, microbuilder commented on samples/ros2_to_step_bridge/src/imu_data_producer.c
> +#include <zephyr.h>
Update required

2022-09-07 12:27 UTC, microbuilder commented on samples/ros2_to_step_bridge/src/imu_data_producer.h
> +#include <zephyr.h>
Update required

2022-09-07 12:27 UTC, microbuilder commented on samples/ros2_to_step_bridge/src/main.c
> +#include <zephyr.h>
Update required

2022-09-07 12:27 UTC, microbuilder commented on samples/ros2_to_step_bridge/src/sensor_node.c
> +#include <zephyr.h>
Update required

2022-09-08 22:37 UTC, uLipe commented
The header namespace issue affects also the ros client library which was patched to be compatible to zephyr, so I'm pointing this PR back to WIP until this change reaches to the microROS module.

2022-10-05 16:17 UTC, uLipe commented
@microbuilder PTAL

CI for this sample it is broken yet, it depends on some work on micro ROS module.

2022-10-09 14:25 UTC, microbuilder commented on samples/ros2_to_step_bridge/README.rst
> +    pip3 install catkin_pkg lark-parser empy colcon-common-extensions
Should we have `--user` here as a best practice?

2022-10-09 14:25 UTC, microbuilder commented on samples/ros2_to_step_bridge/README.rst
> +    west build  -p always -b b_u585i_iot02a  modules/lib/step/samples/ros2_to_step_bridge
Does this require an update to ROS2 to run?

```
[13/274] Performing build step for 'libmicroros_project'
FAILED: libmicroros-prefix/src/libmicroros_project-stamp/libmicroros_project-build /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/libmicroros.a /Users/kevintownsend/Linaro/zephyr/modules/lib/step/build/libmicroros-prefix/src/libmicroros_project-stamp/libmicroros_project-build 
cd /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros && make -f libmicroros.mk "X_CFLAGS=-I/Users/kevintownsend/Linaro/zephyr/zephyr/include -I/Users/kevintownsend/Linaro/zephyr/modules/lib/step/build/zephyr/include/generated -I/Users/kevintownsend/Linaro/zephyr/zephyr/soc/arm/st_stm32/stm32u5 -I/Users/kevintownsend/Linaro/zephyr/zephyr/lib/libc/newlib/include -I/Users/kevintownsend/Linaro/zephyr/zephyr/lib/util/fnmatch/. -I/Users/kevintownsend/Linaro/zephyr/zephyr/drivers -I/Users/kevintownsend/Linaro/zephyr/zephyr/soc/arm/st_stm32/common -I/Users/kevintownsend/Linaro/zephyr/zephyr/subsys/usb/device -I/Users/kevintownsend/Linaro/zephyr/modules/hal/cmsis/CMSIS/Core/Include -I/Users/kevintownsend/Linaro/zephyr/zephyr/modules/hal_nxp/usb/. -I/Users/kevintownsend/Linaro/zephyr/zephyr/modules/hal_nxp/. -I/Users/kevintownsend/Linaro/zephyr/modules/hal/st/sensor/stmemsc/hts221_STdC/driver/ -I/Users/kevintownsend/Linaro/zephyr/modules/hal/st/sensor/stmemsc/iis2mdc_STdC/driver/ -I/Users/kevintownsend/Linaro/zephyr/modules/hal/st/sensor/stmemsc/ism330dhcx_STdC/driver/ -I/Users/kevintownsend/Linaro/zephyr/modules/hal/stm32/stm32cube/stm32u5xx/soc -I/Users/kevintownsend/Linaro/zephyr/modules/hal/stm32/stm32cube/stm32u5xx/drivers/include -I/Users/kevintownsend/Linaro/zephyr/modules/hal/stm32/stm32cube/stm32u5xx/drivers/include/Legacy -I/Users/kevintownsend/Linaro/zephyr/modules/hal/stm32/stm32cube/common_ll/include -I/Users/kevintownsend/Linaro/zephyr/modules/lib/zscilib/include -I/Users/kevintownsend/Linaro/zephyr/modules/lib/step/include -DKERNEL -D__ZEPHYR__=1 -D_FORTIFY_SOURCE=2 -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -DSTM32U585xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DHSE_VALUE=8000000 -fno-strict-aliasing -Os -imacros /Users/kevintownsend/Linaro/zephyr/modules/lib/step/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m33 -mthumb -mabi=aapcs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mfp16-format=ieee --sysroot=/Users/kevintownsend/zephyr-sdk-0.15.0/arm-zephyr-eabi/arm-zephyr-eabi -imacros /Users/kevintownsend/Linaro/zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wformat -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge=CMAKE_SOURCE_DIR -fmacro-prefix-map=/Users/kevintownsend/Linaro/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/Users/kevintownsend/Linaro/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections " "X_CXXFLAGS=-I/Users/kevintownsend/Linaro/zephyr/zephyr/include -I/Users/kevintownsend/Linaro/zephyr/modules/lib/step/build/zephyr/include/generated -I/Users/kevintownsend/Linaro/zephyr/zephyr/soc/arm/st_stm32/stm32u5 -I/Users/kevintownsend/Linaro/zephyr/zephyr/lib/libc/newlib/include -I/Users/kevintownsend/Linaro/zephyr/zephyr/lib/util/fnmatch/. -I/Users/kevintownsend/Linaro/zephyr/zephyr/drivers -I/Users/kevintownsend/Linaro/zephyr/zephyr/soc/arm/st_stm32/common -I/Users/kevintownsend/Linaro/zephyr/zephyr/subsys/usb/device -I/Users/kevintownsend/Linaro/zephyr/modules/hal/cmsis/CMSIS/Core/Include -I/Users/kevintownsend/Linaro/zephyr/zephyr/modules/hal_nxp/usb/. -I/Users/kevintownsend/Linaro/zephyr/zephyr/modules/hal_nxp/. -I/Users/kevintownsend/Linaro/zephyr/modules/hal/st/sensor/stmemsc/hts221_STdC/driver/ -I/Users/kevintownsend/Linaro/zephyr/modules/hal/st/sensor/stmemsc/iis2mdc_STdC/driver/ -I/Users/kevintownsend/Linaro/zephyr/modules/hal/st/sensor/stmemsc/ism330dhcx_STdC/driver/ -I/Users/kevintownsend/Linaro/zephyr/modules/hal/stm32/stm32cube/stm32u5xx/soc -I/Users/kevintownsend/Linaro/zephyr/modules/hal/stm32/stm32cube/stm32u5xx/drivers/include -I/Users/kevintownsend/Linaro/zephyr/modules/hal/stm32/stm32cube/stm32u5xx/drivers/include/Legacy -I/Users/kevintownsend/Linaro/zephyr/modules/hal/stm32/stm32cube/common_ll/include -I/Users/kevintownsend/Linaro/zephyr/modules/lib/zscilib/include -I/Users/kevintownsend/Linaro/zephyr/modules/lib/step/include -DKERNEL -D__ZEPHYR__=1 -D_FORTIFY_SOURCE=2 -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -DSTM32U585xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DHSE_VALUE=8000000 -fno-strict-aliasing -Os -fcheck-new -fno-exceptions -fno-rtti -imacros /Users/kevintownsend/Linaro/zephyr/modules/lib/step/build/zephyr/include/generated/autoconf.h -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m33 -mthumb -mabi=aapcs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mfp16-format=ieee --sysroot=/Users/kevintownsend/zephyr-sdk-0.15.0/arm-zephyr-eabi/arm-zephyr-eabi -imacros /Users/kevintownsend/Linaro/zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wno-unused-but-set-variable -fno-asynchronous-unwind-tables -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge=CMAKE_SOURCE_DIR -fmacro-prefix-map=/Users/kevintownsend/Linaro/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/Users/kevintownsend/Linaro/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections " X_CC=/Users/kevintownsend/zephyr-sdk-0.15.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc X_AR=/Users/kevintownsend/zephyr-sdk-0.15.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-ar X_RANLIB=/Users/kevintownsend/zephyr-sdk-0.15.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-ranlib X_CXX=/Users/kevintownsend/zephyr-sdk-0.15.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++ COMPONENT_PATH=/Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros ZEPHYR_BASE=/Users/kevintownsend/Linaro/zephyr/zephyr PROJECT_BINARY_DIR=/Users/kevintownsend/Linaro/zephyr/modules/lib/step/build/zephyr && /opt/homebrew/Cellar/cmake/3.23.0/bin/cmake -E touch /Users/kevintownsend/Linaro/zephyr/modules/lib/step/build/libmicroros-prefix/src/libmicroros_project-stamp/libmicroros_project-build
. /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/utils.sh; \
        cp /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/colcon.meta /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/configured_colcon.meta; \
        ZEPHYR_CONF_FILE=/Users/kevintownsend/Linaro/zephyr/modules/lib/step/build/zephyr/.config; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_NODES" "rmw_microxrcedds" "RMW_UXRCE_MAX_NODES"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_PUBLISHERS" "rmw_microxrcedds" "RMW_UXRCE_MAX_PUBLISHERS"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_SUBSCRIBERS" "rmw_microxrcedds" "RMW_UXRCE_MAX_SUBSCRIPTIONS"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_CLIENTS" "rmw_microxrcedds" "RMW_UXRCE_MAX_CLIENTS"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_SERVERS" "rmw_microxrcedds" "RMW_UXRCE_MAX_SERVICES"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_RMW_HISTORIC" "rmw_microxrcedds" "RMW_UXRCE_MAX_HISTORY"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_XRCE_DDS_HISTORIC" "rmw_microxrcedds" "RMW_UXRCE_STREAM_HISTORY"; \
        upda [...]

2022-10-10 15:28 UTC, uLipe commented on samples/ros2_to_step_bridge/README.rst
> +    pip3 install catkin_pkg lark-parser empy colcon-common-extensions
I'm supressing user here because it is based on installation of micro ROS module which does not use --user as well.

Not sure if catkin packages would work adding this option, at least for pure ROS2 it did not work.

2022-10-10 15:29 UTC, uLipe commented on samples/ros2_to_step_bridge/README.rst
> +    west build  -p always -b b_u585i_iot02a  modules/lib/step/samples/ros2_to_step_bridge
the ROS2 requirement is a runtime one, it possible to build this wiithout ros2 installed on the machien.

Did you installed the python packages mentioned in the README before building this?

2022-10-25 11:26 UTC, microbuilder commented
I was only able to test this ssh'ing into a Linux box. ROS2 doesn't seem to be compatible out of the box with MacOS and the python3 version it ships with (126 Monterey here on an M1).

Can you perhaps add a note saying that this has only been test on Linux (Ubuntu 22 in my case), and potentially Windows if you have a copy and have tested on that? And that it may have issues with MacOS?

```
This sample has been tested on the following distros:

- Ubuntu 22.04
- Other???

It may work on other operating systems and distros, but ROS2 appears
to have problems with MacOS (Monterey, etc.) and the system version
of Python3. Further testing is required on these operating systems.
```

2022-10-26 18:06 UTC, uLipe commented
Added DNM until new publish API gets merged

2022-11-01 04:54 UTC, uLipe commented
@microbuilder you would test this again? Thanks

2022-11-01 10:50 UTC, microbuilder commented
```bash
$ git fetch linaro     # My remote name here is linaro due to west.yaml
$ git gpr linaro 22    # Local alias to checkout PR 22 from linaro
$ git submodule update --init --recursive 
$ pip3 install catkin_pkg lark-parser empy colcon-common-extensions
$ west build -p always -b b_u585i_iot02a samples/ros2_to_step_bridge
```

Still fails with:

```bash
---
Finished <<< ament_cpplint [2.60s]
Starting >>> ament_lint_auto
Starting >>> ament_cmake_pytest
Starting >>> ament_cmake_google_benchmark
Starting >>> ament_cmake_nose
--- stderr: ament_cmake_gtest
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "/Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/micro_ros_dev/install/ament_cmake_core/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py", line 17, in <module>
    import argparse
  File "/opt/homebrew/lib/python3.10/site-packages/argparse.py", line 93, in <module>
    import re as _re
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
CMake Error at /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/micro_ros_dev/install/ament_cmake_core/share/ament_cmake_core/cmake/ament_cmake_package_templates-extras.cmake:41 (message):
  
  execute_process(/opt/homebrew/Frameworks/Python.framework/Versions/3.10/bin/python3.10
  /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/micro_ros_dev/install/ament_cmake_core/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py
  /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/micro_ros_dev/build/ament_cmake_gtest/ament_cmake_package_templates/templates.cmake)
  returned error code 1
Call Stack (most recent call first):
  /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/micro_ros_dev/install/ament_cmake_core/share/ament_cmake_core/cmake/ament_cmake_coreConfig.cmake:41 (include)
  CMakeLists.txt:5 (find_package)


---
Failed   <<< ament_cmake_gtest [0.52s, exited with code 1]
Aborted  <<< ament_pclint [1.55s]
Aborted  <<< domain_coordinator [1.54s]
Aborted  <<< ament_index_python [1.29s]
Aborted  <<< ament_cmake_lint_cmake [0.52s]
Aborted  <<< ament_lint_auto [0.47s]
Aborted  <<< ament_cmake_pytest [0.46s]
Aborted  <<< ament_clang_tidy [1.72s]
Aborted  <<< ament_cmake_google_benchmark [0.47s]
Aborted  <<< ament_cmake_nose [0.46s]
```

2022-11-01 11:00 UTC, microbuilder commented
> ```shell
> $ git fetch linaro     # My remote name here is linaro due to west.yaml
> $ git gpr linaro 22    # Local alias to checkout PR 22 from linaro
> $ git submodule update --init --recursive 
> $ pip3 install catkin_pkg lark-parser empy colcon-common-extensions
> $ west build -p always -b b_u585i_iot02a samples/ros2_to_step_bridge
> ```

I also tried recloning the submodules with the below:

```bash
$ git submodule sync
$ git submodule deinit -f .
$ git submodule update --init --recursive
```

... but same failure/error/

Then this, which pulls some changes in:

```bash
$ git submodule update --remote --merge
Updating 1a5f55e..2cfb902
Fast-forward
 modules/libmicroros/libmicroros.mk                                       |  3 ++-
 modules/libmicroros/microros_transports/serial-usb/microros_transports.c |  6 +++---
 modules/libmicroros/microros_transports/serial/microros_transports.c     |  4 ++--
 modules/libmicroros/microros_transports/udp/microros_transports.c        | 11 +++++++----
 modules/libmicroros/zephyr_toolchain.cmake.in                            |  4 ++--
 src/main.c                                                               |  4 ++--
 6 files changed, 18 insertions(+), 14 deletions(-)
Submodule path 'samples/ros2_to_step_bridge/micro_ros_zephyr_module': merged in '2cfb9028967ef575c50d596e5e5ba5e0d5a80886'
```

And different error, but same warning about `AttributeError: module 'enum' has no attribute 'IntFlag'`:

```
. /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/utils.sh; \
        cp /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/colcon.meta /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/configured_colcon.meta; \
        ZEPHYR_CONF_FILE=/Users/kevintownsend/Linaro/zephyr/modules/lib/step/build/zephyr/.config; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_NODES" "rmw_microxrcedds" "RMW_UXRCE_MAX_NODES"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_PUBLISHERS" "rmw_microxrcedds" "RMW_UXRCE_MAX_PUBLISHERS"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_SUBSCRIBERS" "rmw_microxrcedds" "RMW_UXRCE_MAX_SUBSCRIPTIONS"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_CLIENTS" "rmw_microxrcedds" "RMW_UXRCE_MAX_CLIENTS"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_SERVERS" "rmw_microxrcedds" "RMW_UXRCE_MAX_SERVICES"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_RMW_HISTORIC" "rmw_microxrcedds" "RMW_UXRCE_MAX_HISTORY"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_XRCE_DDS_HISTORIC" "rmw_microxrcedds" "RMW_UXRCE_STREAM_HISTORY"; \
        update_meta_from_zephyr_config "CONFIG_MICROROS_XRCE_DDS_MTU" "microxrcedds_client" "UCLIENT_CUSTOM_TRANSPORT_MTU"; \
        update_meta "microxrcedds_client" "UCLIENT_PROFILE_SERIAL=OFF"; \
        update_meta "microxrcedds_client" "UCLIENT_PROFILE_UDP=OFF"; \
        update_meta "microxrcedds_client" "UCLIENT_PROFILE_TCP=OFF"; \
        update_meta "microxrcedds_client" "UCLIENT_PROFILE_CUSTOM_TRANSPORT=ON"; \
        update_meta "microxrcedds_client" "UCLIENT_PROFILE_STREAM_FRAMING=ON"; \
        update_meta "rmw_microxrcedds" "RMW_UXRCE_TRANSPORT=custom";
rm -f /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/zephyr_toolchain.cmake; \
        cat /Users/kevintownsend/Linaro/zephyr/modules/lib/step/samples/ros2_to_step_bridge/micro_ros_zephyr_module/modules/libmicroros/zephyr_toolchain.cmake.in | \
                sed "s/@CMAKE_C_COMPILER@/\/Users\/kevintownsend\/zephyr-sdk-0.15.0\/arm-zephyr-eabi\/bin\/arm-zephyr-eabi-gcc/g" | \
                sed "s/@CMAKE_CXX_COMPILER@/\/Users\/kevintownsend\/zephyr-sdk-0.15.0\/arm-zephyr-eabi\/bin\/arm-zephyr-eabi-g++/g" | \
                sed "s/@CMAKE_SYSROOT@/\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/lib\/step\/samples\/ros2_to_step_bridge\/micro_ros_zephyr_module\/modules\/libmicroros/g" | \
                sed "s/@CFLAGS@/-c -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/include\/posix -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/lib\/step\/build\/zephyr\/include\/generated -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/include -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/lib\/step\/build\/zephyr\/include\/generated -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/soc\/arm\/st_stm32\/stm32u5 -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/lib\/libc\/newlib\/include -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/lib\/util\/fnmatch\/. -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/drivers -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/soc\/arm\/st_stm32\/common -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/subsys\/usb\/device -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/hal\/cmsis\/CMSIS\/Core\/Include -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/modules\/hal_nxp\/usb\/. -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/modules\/hal_nxp\/. -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/hal\/st\/sensor\/stmemsc\/hts221_STdC\/driver\/ -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/hal\/st\/sensor\/stmemsc\/iis2mdc_STdC\/driver\/ -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/hal\/st\/sensor\/stmemsc\/ism330dhcx_STdC\/driver\/ -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/hal\/stm32\/stm32cube\/stm32u5xx\/soc -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/hal\/stm32\/stm32cube\/stm32u5xx\/drivers\/include -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/hal\/stm32\/stm32cube\/stm32u5xx\/drivers\/include\/Legacy -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/hal\/stm32\/stm32cube\/common_ll\/include -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/lib\/zscilib\/include -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/lib\/step\/include -DKERNEL -D__ZEPHYR__=1 -D_FORTIFY_SOURCE=2 -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -DSTM32U585xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DHSE_VALUE=8000000 -fno-strict-aliasing -Os -imacros \/Users\/kevintownsend\/Linaro\/zephyr\/modules\/lib\/step\/build\/zephyr\/include\/generated\/autoconf.h -ffreestanding -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m33 -mthumb -mabi=aapcs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mfp16-format=ieee --sysroot=\/Users\/kevintownsend\/zephyr-sdk-0.15.0\/arm-zephyr-eabi\/arm-zephyr-eabi -imacros \/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/include\/zephyr\/toolchain\/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wformat -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/lib\/step\/samples\/ros2_to_step_bridge=CMAKE_SOURCE_DIR -fmacro-prefix-map=\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr=ZEPHYR_BASE -fmacro-prefix-map=\/Users\/kevintownsend\/Linaro\/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections /g" | \
                sed "s/@CXXFLAGS@/-c -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/include\/posix -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/lib\/step\/build\/zephyr\/include\/generated -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/include -I\/Users\/kevintownsend\/Linaro\/zephyr\/modules\/lib\/step\/build\/zephyr\/include\/generated -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/soc\/arm\/st_stm32\/stm32u5 -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/lib\/libc\/newlib\/include -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/lib\/util\/fnmatch\/. -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/drivers -I\/Users\/kevintownsend\/Linaro\/zephyr\/zephyr\/soc\/arm\/st_stm32\/common -I\/Users\/kevintown [...]

2022-11-01 11:40 UTC, uLipe commented
I see you are building for macOS I forgot to mention in the readme that ros2 are coupled to a particular ubuntu / debian LTS and humble is coupled to 22.04

Would you able to try this in Ubuntu environnement?

I'll update the readme with this information.

2022-11-01 11:54 UTC, microbuilder commented
> I see you are building for macOS I forgot to mention in the readme that ros2 are coupled to a particular ubuntu / debian LTS and humble is coupled to 22.04
> 
> Would you able to try this in Ubuntu environnement?
> 
> I'll update the readme with this information.

NP, I have an Ubuntu 22.04 VM I use as well, I'll test on that.

2022-11-03 15:17 UTC, uLipe commented
It seems the problem is related to build this on the ARM based laptops, Will add this restriction on the README.

2022-11-03 21:42 UTC, uLipe commented
@microbuilder PTAL now we have CI to help us to attest build of this sample.

2022-11-04 12:11 UTC, microbuilder commented on samples/ros2_to_step_bridge/README.rst
> +* MacOS version
Please just remove this until Arm works. Thanks.

2022-11-04 12:11 UTC, microbuilder commented on samples/ros2_to_step_bridge/README.rst
> +For now ARM based host computers are not able to build this sample.
```suggestion
For now Arm-based host computers are not able to build this sample.
```

2022-11-04 13:52 UTC, uLipe commented
@microbuilder just waiting to CI to merge it.

2022-11-04 14:07 UTC, merged