proc_manager: replace poll thread by workqueue plus timer
Linaro/step pull request #23
Opened 2022-08-11 22:39 UTC by uLipe

2022-08-11 22:39 UTC, uLipe commented
@microbuilder PTAL

2022-08-11 23:22 UTC, microbuilder requested changes

2022-08-11 23:22 UTC, microbuilder commented on Kconfig.step
> +	  Sets the priority level for the polling handler.A positive value indicates that this is
Do we want to limit this to a range of -4 and 0?

2022-08-11 23:22 UTC, microbuilder commented on include/step/proc_mgr.h
> + *                  (Deprecated), currrently noop.
Typo

2022-08-11 23:22 UTC, microbuilder commented on include/step/sample_pool.h
> + * @return positive number indicating the amout of pendin messages, 0 otherwise.
Pending

2022-08-12 07:57 UTC, microbuilder commented
@uLipe Can you update the Zephyr header references to start with `zephyr/zephyr.h` (etc.)? With the latest Zephyr code, builds will fail:

```
/Users/kevintownsend/Linaro/zephyr/modules/lib/step/tests/src/floatcheck.h:17:10: fatal error: zephyr.h: No such file or directory
   17 | #include <zephyr.h>
      |          ^~~~~~~~~~
compilation terminated.
[16/139] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc7_sw.c.obj
[17/139] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc32c_sw.c.obj
[18/139] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc32_sw.c.obj
[19/139] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc8_sw.c.obj
[20/139] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/crc16_sw.c.obj
[21/139] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf_packaged.c.obj
ninja: build stopped: subcommand failed.

INFO    - Total complete:    1/   1  100%  skipped:    0, failed:    0
INFO    - 0 of 1 test configurations passed (0.00%), 1 failed, 0 skipped with 0 warnings in 4.66 seconds
INFO    - In total 21 test cases were executed, 0 skipped on 1 out of total 488 platforms (0.20%)
INFO    - 0 test configurations executed on platforms, 1 test configurations were only built.
INFO    - Saving reports...
INFO    - Writing JSON report /Users/kevintownsend/Linaro/zephyr/modules/lib/step/twister-out/twister.json
INFO    - Writing xunit report /Users/kevintownsend/Linaro/zephyr/modules/lib/step/twister-out/twister.xml...
INFO    - Writing xunit report /Users/kevintownsend/Linaro/zephyr/modules/lib/step/twister-out/twister_report.xml...
INFO    - Run completed
```

2022-08-12 12:07 UTC, uLipe commented
Ahhh that is true I suffered same problem inside of other PR I submit.

Will update it.

2022-08-12 15:54 UTC, uLipe commented on Kconfig.step
> +	  Sets the priority level for the polling handler.A positive value indicates that this is
I hope so, because the idea of nodes are to execute as soon the get deferred to avoid high congestion in the worqueue.

2022-08-12 15:57 UTC, microbuilder commented on Kconfig.step
> +	  Sets the priority level for the polling handler.A positive value indicates that this is
Perhaps remove the comment on positive values, then, if we’re setting a ceiling of 0, and just state the range?

2022-08-12 18:15 UTC, uLipe commented
@microbuilder PTAL again.

2022-09-01 17:12 UTC, microbuilder requested changes
Looks like there are still some header errors here:

```bash
$ twister --inline-logs \
  -p qemu_cortex_m3 \
  -T tests
```

```bash
/Users/kevintownsend/Linaro/zephyr/modules/lib/step/tests/src/floatcheck.h:17:10: fatal error: zephyr.h: No such file or directory
   17 | #include <zephyr.h>
```

2022-09-05 12:09 UTC, microbuilder commented
@uLipe I was going to make a PR for the Zephyr header cleanup since it's quick to do, but that will make a conflict with the partial changes you've started here, so lets just roll it all up into this PR. Thanks!

2022-09-05 12:11 UTC, microbuilder commented
Also ... further changes likely required in the future, renaming `<zephyr/zephyr.h` to `<zephyr/kernel.h>` but we can sort that out when the changes is merged in and we've moved to a major release using the new name. 

See: https://github.com/zephyrproject-rtos/zephyr/pull/49510

2022-09-05 14:33 UTC, microbuilder commented
@uLipe That PR above was just merged, so maybe we should switch to the latest Zephyr commit, and just update to `kernel.h` to solve this hopefully once and for all?

2022-09-05 14:48 UTC, uLipe commented
Yes agreed, I will take the opportunity to update all zephyr headers, regardless samples or not (zephyr namespace is only required if you build twister, applications out of tree actually does not need it)

And then we can check the header cleanup.

2022-09-09 15:05 UTC, uLipe commented
@microbuilder PTAL

2022-09-09 15:38 UTC, microbuilder approved these changes

2022-09-09 15:38 UTC, merged